In [1]:
##Loading datasets

In [2]:
import pandas as pd
#loading dolly2.0
df1 = pd.read_json("hf://datasets/databricks/databricks-dolly-15k/databricks-dolly-15k.jsonl", lines=True)

In [3]:
#share gpt conversation loading
df2 = pd.read_json("hf://datasets/theblackcat102/sharegpt-english/train.jsonl", lines=True)

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15011 entries, 0 to 15010
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   instruction  15011 non-null  object
 1   context      15011 non-null  object
 2   response     15011 non-null  object
 3   category     15011 non-null  object
dtypes: object(4)
memory usage: 469.2+ KB

In [5]:
df3=pd.read_csv("daily_dialogue_train.csv")

In [6]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11118 entries, 0 to 11117
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   dialog   11118 non-null  object
 1   act      11118 non-null  object
 2   emotion  11118 non-null  object
dtypes: object(3)
memory usage: 260.7+ KB

In [7]:
df4=pd.read_csv("test.csv")

In [8]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   dialog   1000 non-null   object
 1   act      1000 non-null   object
 2   emotion  1000 non-null   object
dtypes: object(3)
memory usage: 23.6+ KB

In [9]:
df3 = pd.concat([df3, df4], ignore_index=True)

In [10]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12118 entries, 0 to 12117
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   dialog   12118 non-null  object
 1   act      12118 non-null  object
 2   emotion  12118 non-null  object
dtypes: object(3)
memory usage: 284.1+ KB

In [11]:
#preprocessing datasets

In [12]:
df1.info(),df2.info(),df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15011 entries, 0 to 15010
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   instruction  15011 non-null  object
 1   context      15011 non-null  object
 2   response     15011 non-null  object
 3   category     15011 non-null  object
dtypes: object(4)
memory usage: 469.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50496 entries, 0 to 50495
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   conversations  50496 non-null  object
 1   id             50496 non-null  object
 2   lang           50496 non-null  object
dtypes: object(3)
memory usage: 1.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12118 entries, 0 to 12117
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   dialog   12118 non-null  object
 1   act      12118 non-null  object
 2   emotion  12118 non-null  object
dtypes: object(3)
memory usage: 284.1+ KB

(None, None, None)

In [14]:
df1.head()

,instruction,context,response,category
0,When did Virgin Australia start operating?,"Virgin Australia, the trading name of Virgin A...",Virgin Australia commenced services on 31 Augu...,closed_qa
1,Which is a species of fish? Tope or Rope,,Tope,classification
2,Why can camels survive for long without water?,,Camels use the fat in their humps to keep them...,open_qa
3,"Alice's parents have three daughters: Amy, Jes...",,The name of the third daughter is Alice,open_qa
4,When was Tomoaki Komorida born?,Komorida was born in Kumamoto Prefecture on Ju...,"Tomoaki Komorida was born on July 10,1981.",closed_qa

In [15]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15011 entries, 0 to 15010
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   instruction  15011 non-null  object
 1   context      15011 non-null  object
 2   response     15011 non-null  object
 3   category     15011 non-null  object
dtypes: object(4)
memory usage: 469.2+ KB

In [16]:
df1=df1[['instruction','response']]

In [18]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15011 entries, 0 to 15010
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   instruction  15011 non-null  object
 1   response     15011 non-null  object
dtypes: object(2)
memory usage: 234.7+ KB

In [19]:
import pandas as pd
import json

# Assuming df1 is already loaded
data1 = [
    {"prompt": row["instruction"], "response": row["response"]}
    for _, row in df1.iterrows()
]

In [26]:
df2=df2['conversations']

In [30]:
df2.info()

<class 'pandas.core.series.Series'>
RangeIndex: 50496 entries, 0 to 50495
Series name: conversations
Non-Null Count  Dtype
--------------  -----
50496 non-null  object
dtypes: object(1)
memory usage: 394.6+ KB

In [34]:
df2

0        [{'user': 'human', 'text': 'A + B means A is t...
1        [{'user': 'human', 'text': 'Web search results...
2        [{'user': 'human', 'text': 'who is andrew tate...
3        [{'user': 'human', 'text': 'Web search results...
4        [{'user': 'human', 'text': 'write a walmart pr...
                               ...
50491    [{'user': 'human', 'text': '<div><p class="">I...
50492    [{'user': 'human', 'text': '<div><p class="">C...
50493    [{'user': 'human', 'text': '<div><p class="">w...
50494    [{'user': 'human', 'text': '<div><p class="">w...
50495    [{'user': 'human', 'text': '<div><p class="">G...
Name: conversations, Length: 50496, dtype: object

In [36]:
data2 = []
for convo in df2:
    if isinstance(convo, list) and len(convo) == 2:
        human = next((item["text"] for item in convo if item["user"] == "human"), None)
        gpt = next((item["text"] for item in convo if item["user"] == "gpt"), None)
        if human and gpt:
            data2.append({
                "prompt": human.strip(),
                "response": gpt.strip()
            })

In [41]:
df3['dialog'][0]

'[\'Say , Jim , how about going for a few beers after dinner ? \'\n \' You know that is tempting but is really not good for our fitness . \'\n \' What do you mean ? It will help us to relax . \'\n " Do you really think so ? I don\'t . It will just make us fat and act silly . Remember last time ? "\n " I guess you are right.But what shall we do ? I don\'t feel like sitting at home . "\n \' I suggest a walk over to the gym where we can play singsong and meet some of our friends . \'\n " That\'s a good idea . I hear Mary and Sally often go there to play pingpong.Perhaps we can make a foursome with them . "\n \' Sounds great to me ! If they are willing , we could ask them to go dancing with us.That is excellent exercise and fun , too . \'\n " Good.Let \' s go now . " \' All right . \']'

In [58]:
import random
import json

# Assuming data1 and data2 are both lists of dicts like: [{"prompt": ..., "response": ...}, ...]

# Combine them
final_data = data1 + data2

# Shuffle to mix entries
random.shuffle(final_data)

In [59]:
with open("human_dataset.json", "w", encoding="utf-8") as f:
    json.dump(final_data, f, ensure_ascii=False, indent=2)

In [60]:
#importing dataset

In [61]:
df=pd.read_json("human_dataset.json")

In [62]:
df.head()

,prompt,response
0,Give me a list of five healthy snacks for kids,"Peanut butter, cheese, milk, fruit and popcorn"
1,What are some good birthday presents for my ne...,Here are a few ideas for birthday presents for...
2,set up couchdb for me in flask restapi ubuntu ...,Setting up CouchDB in a Flask-based REST API o...
3,What is the experience of Microsoft Office use...,Microsoft Office has been an enterprise softwa...
4,"Given this paragraph about Chinese cuisine, te...",The modern Chinese cuisine were broken down in...

In [63]:
#combination of datasets: databricks-dolly-15k and sharegpt-english